name: A workflow for my Hello World file
on: 
  push:
  pull_request:

jobs:
  # checkout:
  #   steps:
  #     # current branch head, not detached.
  #     - uses: actions/checkout@v1
  #       with:
  #         # ref: ${{ github.event.pull_request.head.sha }}
  #         fetch-depth: 0

  # name: Extract Branch Name
  # run: echo "::set-env name=BRANCH::$(echo ${GITHUB_REF##*/})"

  build:
    name: Hello world action
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      # default branch main, not master.
      - name: default branch
        run: git config --global init.defaultBranch main

      # if Pull Request
      - uses: actions/checkout@v1
        # if: github.event.pull_request
        # with:
        #   ref: ${{ github.event.pull_request.head.ref }}
        #   fetch-depth: 0

      # # if branch
      - uses: actions/checkout@v1
        if: "!contains(github.ref, 'refs/pull')"
        with:
          ref: ${{ github.ref }}
          # fetch-depth: 0

      # - name: fix
      #   run: "git checkout ${{ github.ref }}"

      # local custom action
      - uses: ./action-a
        with:
          MY_NAME: "Mona"

      - name: Validate
        env:
          FOLDER: test
        run: |
          pwd
          git status
          git pull --tags --ff-only

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: "false"
      #     github-token: ${{ secrets.github_token }}
      #     git-message: 'chore(release): {version}'
      #     git-user-name: 'Awesome Changelog Action'
      #     git-user-email: 'awesome_changelog@github.actions.com'
      #     preset: 'angular'
      #     tag-prefix: 'v'
      #     output-file: 'MY_CUSTOM_CHANGELOG.md'
      #     release-count: '10'
      #     version-file: './my_custom_version_file.json'
      #     version-path: 'path.to.version'
      #     skip-on-empty: 'false'
      #     skip-version-file: 'false'
      #     skip-commit: 'false'
      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

      - name: Report
        env:
          tag_name: ${{ steps.changelog.outputs.tag }}
        run: |
          echo $tag_name
