name: A workflow for my Hello World file
on: 
  push:
  pull_request:

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"

      # - name: Conventional Changelog Action
      #   uses: TriPSs/conventional-changelog-action@v3
      #   with:
      #     github-token: ${{ secrets.github_token }}
      #     git-message: 'chore(release): {version}'
      #     git-user-name: 'Awesome Changelog Action'
      #     git-user-email: 'awesome_changelog@github.actions.com'
      #     preset: 'angular'
      #     tag-prefix: 'v'
      #     output-file: 'MY_CUSTOM_CHANGELOG.md'
      #     release-count: '10'
      #     version-file: './my_custom_version_file.json'
      #     version-path: 'path.to.version'
      #     skip-on-empty: 'false'
      #     skip-version-file: 'false'
      #     skip-commit: 'false'



      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: "false"

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
